services:
  dockterm:
    image: ghcr.io/iaziz786/dockterm@sha256:5bc2e7949e3c223d7d73003c85b4b64bf06c8a4aaa30ec92d6be9c84aeeb521a
    platform: linux/amd64
    ports:
      - "2222:22"
      # general port for the development, add your own
      - "3000:3000"
      - "8080:8080"
    volumes:
      - ./.docker-keys:/home/developer/.ssh:rw
      - dockterm-home:/home/developer
      - code:/home/developer/Code
    restart: unless-stopped

volumes:
  dockterm-home:
  code:
